import {useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {api} from '../api';
import {useCart} from '../context/CartContext';

export default function Checkout(){
  const {items,subtotal,clear}=useCart();const nav=useNavigate();const [form,setForm]=useState({fullName:'',phone:'',address:'',city:'',state:'Rajasthan',pincode:'',paymentMethod:'COD'});const [credit,setCredit]=useState(null);const [error,setError]=useState('');const delivery=subtotal>=499?0:49;const total=subtotal+delivery;
  useEffect(()=>{api('/paylater').then(setCredit).catch(()=>{})},[]);
  const canPayLater=credit?.status==='approved'&&credit.available>=total;
  async function submit(e){e.preventDefault();if(!items.length)return;try{const {paymentMethod,...shippingAddress}=form;await api('/orders',{method:'POST',body:JSON.stringify({items:items.map(i=>({product:i._id,quantity:i.qty})),shippingAddress,paymentMethod})});clear();nav('/orders')}catch(e){setError(e.message)}}
  return <main className="section"><div className="page-title"><span className="eyebrow">SECURE CHECKOUT</span><h1>Review & place order</h1></div><div className="checkout-layout"><form className="form-card checkout-card" onSubmit={submit}><h2>Delivery details</h2>{error&&<div className="alert">{error}</div>}<div className="form-grid">{['fullName','phone','address','city','state','pincode'].map(k=><label key={k}>{k.replace(/([A-Z])/g,' $1')}<input required value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><div className="payment-title"><h2>Payment</h2><span>Choose one option</span></div><div className="payment-options"><label className={form.paymentMethod==='COD'?'selected':''}><input type="radio" name="payment" checked={form.paymentMethod==='COD'} onChange={()=>setForm({...form,paymentMethod:'COD'})}/><span>💵</span><div><b>Cash on Delivery</b><small>Pay when your order arrives</small></div></label><label className={form.paymentMethod==='UPI'?'selected':''}><input type="radio" name="payment" checked={form.paymentMethod==='UPI'} onChange={()=>setForm({...form,paymentMethod:'UPI'})}/><span>📱</span><div><b>UPI</b><small>Demo online payment option</small></div></label><label className={`${form.paymentMethod==='PAYLATER'?'selected':''} ${!canPayLater?'disabled':''}`}><input disabled={!canPayLater} type="radio" name="payment" checked={form.paymentMethod==='PAYLATER'} onChange={()=>setForm({...form,paymentMethod:'PAYLATER'})}/><span>₹</span><div><b>SBN PayLater</b><small>{canPayLater?`₹${credit.available.toLocaleString()} available`:(credit?.status==='approved'?'Not enough available credit':'Manual approval required')}</small></div></label></div>{credit&&<div className="checkout-credit-note">PayLater outstanding: ₹{credit.used.toLocaleString()} · Approved limit: ₹{credit.limit.toLocaleString()}</div>}<button>Place Order · ₹{total}</button></form><aside className="summary order-summary-new"><h2>Your order</h2>{items.map(i=><p key={i._id}><span>{i.name} × {i.qty}</span><b>₹{i.price*i.qty}</b></p>)}<hr/><p><span>Delivery</span><b>{delivery?'₹49':'FREE'}</b></p><p className="total"><span>Total</span><b>₹{total}</b></p><small>By placing this order you agree to SBN Kirana terms and applicable PayLater terms.</small></aside></div></main>}
