import {useEffect,useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {api} from '../api';
import {useCart} from '../context/CartContext';

const productIdOf=value=>String(value?._id||value||'');
export default function Orders(){
  const [orders,setOrders]=useState([]);const [reviewOpps,setReviewOpps]=useState([]);const [busy,setBusy]=useState('');const [msg,setMsg]=useState('');const {addToCart}=useCart();const nav=useNavigate();
  const load=()=>Promise.all([api('/orders/mine'),api('/reviews/opportunities')]).then(([o,r])=>{setOrders(o||[]);setReviewOpps(r?.opportunities||[])}).catch(()=>{});
  useEffect(()=>{let active=true;const refresh=()=>{if(active)load()};refresh();const timer=setInterval(refresh,60000);const onFocus=()=>refresh();const onReviews=()=>refresh();window.addEventListener('focus',onFocus);window.addEventListener('sbn:reviews-updated',onReviews);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',onFocus);window.removeEventListener('sbn:reviews-updated',onReviews)}},[]);
  const reviewIds=useMemo(()=>new Set(reviewOpps.map(x=>productIdOf(x.product))),[reviewOpps]);
  async function buyAgain(order){setBusy(order._id);setMsg('');try{let added=0;let skipped=0;for(const item of order.items){if(!item.product){skipped++;continue}try{const p=await api(`/products/${productIdOf(item.product)}`);if(!p?.stock){skipped++;continue}const qty=Math.min(Number(item.quantity)||1,p.stock);for(let n=0;n<qty;n++)addToCart(p);added+=qty}catch{skipped++}}if(!added)return setMsg('These products are currently unavailable.');setMsg(`${added} item${added===1?'':'s'} added to cart${skipped?` · ${skipped} unavailable`:''}.`);nav('/cart')}finally{setBusy('')}}
  function rateProduct(productId){nav(`/product/${productId}#rate-product`)}
  return <main className="section"><div className="page-title"><span className="eyebrow">Account</span><h1>My Orders</h1><p>Track purchases and quickly rebuild a previous basket using current prices and stock.</p></div>{msg&&<div className="buy-again-msg">{msg}</div>}
    {reviewOpps.length>0&&<section id="review-reminders" className="review-reminder-panel"><div className="review-reminder-head"><div><span>🔔 DELIVERED ORDER</span><h2>How was your purchase?</h2><p>{reviewOpps.length} delivered product{reviewOpps.length===1?' is':'s are'} ready for your rating and suggestion.</p></div><b>{reviewOpps.length}</b></div><div className="review-reminder-items">{reviewOpps.map(x=><article key={productIdOf(x.product)}>{x.image&&<img src={x.image} alt=""/>}<div><b>{x.name}</b><small>Order #{String(x.orderId||'').slice(-8).toUpperCase()} · Delivered</small></div><button onClick={()=>rateProduct(productIdOf(x.product))}>Rate & Suggest →</button></article>)}</div></section>}
    <div className="orders">{orders.map(o=><article className="order-card" key={o._id}><div className="order-head"><div><small>ORDER</small><b>#{o._id.slice(-8).toUpperCase()}</b></div><div><small>DATE</small><b>{new Date(o.createdAt).toLocaleDateString('en-IN')}</b></div><div><small>TOTAL</small><b>₹{o.total}</b></div><span className={`status ${o.status.toLowerCase()}`}>{o.status}</span></div>{o.items.map(i=>{const pid=productIdOf(i.product);const canRate=o.status==='Delivered'&&reviewIds.has(pid);return <div className="order-line" key={i._id}><span>{i.name} × {i.quantity}</span><div className="order-line-actions"><b>₹{i.price*i.quantity}</b>{canRate&&<button onClick={()=>rateProduct(pid)}>★ Rate & Suggest</button>}</div></div>})}<div className="order-repeat"><span>{o.status==='Delivered'?'Delivered successfully. Need these groceries again?':'Need the same groceries again?'}</span><button disabled={busy===o._id} onClick={()=>buyAgain(o)}>{busy===o._id?'Checking stock...':'↻ Buy Again'}</button></div></article>)}{!orders.length&&<div className="empty"><h2>No orders yet</h2><p>Your placed orders will appear here.</p></div>}</div></main>
}
