import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api';

export default function PayLater(){
  const [data,setData]=useState(null);const [amount,setAmount]=useState(3000);const [msg,setMsg]=useState('');const [error,setError]=useState('');
  const load=()=>api('/paylater').then(setData).catch(e=>setError(e.message));
  useEffect(()=>{load()},[]);
  async function request(e){e.preventDefault();setError('');setMsg('');try{const r=await api('/paylater/request',{method:'POST',body:JSON.stringify({requestedLimit:Number(amount)})});setMsg(r.message);load()}catch(e){setError(e.message)}}
  if(!data)return <main className="section"><div className="loading">Loading PayLater...</div></main>;
  const pct=data.limit?Math.min((data.used/data.limit)*100,100):0;
  const restricted=['suspended','banned','blocked'].includes(data.status);
  return <main className="paylater-page">
    <section className="credit-hero"><div><span className="credit-chip">SBN PAYLATER</span><h1>Shop today.<br/>Pay from your store credit later.</h1><p>A simple SBN Kirana store-credit facility. Every request, limit change and account restriction is reviewed manually by store management.</p></div><div className="credit-card"><small>AVAILABLE CREDIT</small><strong>₹{data.available.toLocaleString()}</strong><div className="credit-meter"><i style={{width:`${pct}%`}}></i></div><span>Used ₹{data.used.toLocaleString()} of ₹{data.limit.toLocaleString()}</span></div></section>
    <section className="credit-grid">
      <div className="credit-panel"><h2>Account status</h2><div className={`credit-status ${data.status}`}>{data.status.replaceAll('_',' ').toUpperCase()}</div><p>Requested limit: <b>₹{data.requestedLimit.toLocaleString()}</b></p><p>Approved limit: <b>₹{data.limit.toLocaleString()}</b></p><p>Outstanding: <b>₹{data.used.toLocaleString()}</b></p><p>Due date: <b>{data.dueDate?new Date(data.dueDate).toLocaleDateString('en-IN'):'No amount due'}</b></p><p>Recovery status: <b>{String(data.recoveryStatus||'current').replaceAll('_',' ')}</b></p>{data.nextFollowUpAt&&<p>Next follow-up: <b>{new Date(data.nextFollowUpAt).toLocaleDateString('en-IN')}</b></p>}{data.note&&<div className="credit-note">Store note: {data.note}</div>}</div>
      <div className="credit-panel"><h2>{data.status==='approved'?'PayLater is active':restricted?'PayLater access is restricted':data.status==='pending'?'Request under review':'Request PayLater'}</h2>{data.status==='approved'?<><p>You can select <b>SBN PayLater</b> at checkout whenever your available limit covers the order total.</p><div className="safe-credit">✓ Manual store approval<br/>✓ No automatic credit scoring<br/>✓ Outstanding balance visible anytime</div></>:restricted?<><p>Your PayLater access is currently restricted after manual store review. Your outstanding balance remains visible and payable.</p><div className="safe-credit">Contact support if you have already paid, need repayment help, or want to raise a dispute.</div><Link className="outline-btn" to="/contact">Contact Support</Link></>:data.status==='pending'?<><p>Your request is waiting for manual review by store management.</p><div className="safe-credit">No automatic approval or credit scoring is used.</div></>:<form onSubmit={request}><label>Requested store-credit limit<input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button>Submit for manual review</button></form>}{msg&&<div className="notice">{msg}</div>}{error&&<div className="alert">{error}</div>}</div>
    </section>
    <section className="credit-grid"><div className="credit-panel"><h2>Payment recovery policy</h2><p>If a balance becomes due, the store may use reasonable reminders by phone, message or email and may ask you to confirm a repayment date. Any home visit should be pre-notified, respectful and lawful.</p><div className="safe-credit">✓ You can dispute a payment/account issue<br/>✓ Payments update only after receipt is confirmed<br/>✓ Legal review does not mean automatic legal proceedings<br/>✓ No harassment, intimidation, public shaming or misleading threats</div><Link className="outline-btn" to="/info/recovery-policy">Read full recovery policy</Link></div><div className="credit-panel"><h2>Need repayment help?</h2><p>If you cannot pay the full balance immediately, contact store support and explain the situation. Store management can manually review your account and record a repayment discussion or promised payment date.</p><Link className="outline-btn" to="/contact">Contact SBN Support</Link></div></section>
  </main>
}
