import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {api} from '../api';
import {useCart} from '../context/CartContext';
import ProductCard from '../components/ProductCard';

const WISH='sbn_wishlist';
export default function ProductDetail(){
  const {id}=useParams();const {addToCart}=useCart();const [product,setProduct]=useState(null);const [related,setRelated]=useState([]);const [error,setError]=useState('');const [saved,setSaved]=useState(false);
  useEffect(()=>{setError('');api(`/products/${id}`).then(p=>{setProduct(p);document.title=`${p.name} | SBN Kirana`;const d=document.querySelector('meta[name="description"]');if(d)d.setAttribute('content',`${p.name} ${p.unit||''} at SBN Kirana. ${p.description||'Shop groceries and daily essentials online.'}`);const ids=JSON.parse(localStorage.getItem(WISH)||'[]');setSaved(ids.includes(p._id));return api(`/products?category=${encodeURIComponent(p.category)}`)}).then(list=>setRelated((list||[]).filter(x=>x._id!==id).slice(0,4))).catch(e=>setError(e.message));return()=>{document.title='SBN Kirana | Online Grocery & Daily Essentials'}},[id]);
  function toggleSave(){if(!product)return;let ids=JSON.parse(localStorage.getItem(WISH)||'[]');ids=ids.includes(product._id)?ids.filter(x=>x!==product._id):[product._id,...ids];localStorage.setItem(WISH,JSON.stringify(ids));setSaved(ids.includes(product._id))}
  function share(){const url=window.location.href;const text=encodeURIComponent(`Check ${product.name} on SBN Kirana – ₹${product.price} ${url}`);window.open(`https://wa.me/?text=${text}`,'_blank','noopener,noreferrer')}
  if(error)return <main className="section"><div className="alert">{error}</div></main>;
  if(!product)return <main className="section"><div className="loading">Loading product...</div></main>;
  const save=Math.max((product.mrp||0)-(product.price||0),0);return <main className="product-detail-page"><div className="product-breadcrumb"><Link to="/">Home</Link> / <Link to="/products">Products</Link> / <span>{product.name}</span></div><section className="product-detail-card"><div className="product-detail-image"><img src={product.image} alt={product.name}/>{product.discount>0&&<span>{product.discount}% OFF</span>}</div><div className="product-detail-copy"><span className="product-detail-category">{product.category}</span><h1>{product.name}</h1><p className="product-detail-unit">{product.unit}</p><div className="detail-price"><strong>₹{product.price}</strong>{product.mrp>product.price&&<del>₹{product.mrp}</del>}</div>{save>0&&<div className="detail-saving">You save ₹{save}</div>}<p className="detail-description">{product.description||'Quality grocery and daily essential from SBN Kirana.'}</p><div className={`detail-stock ${product.stock?'in':'out'}`}>{product.stock?`✓ In stock · ${product.stock} available`:'Out of stock'}</div><div className="detail-actions"><button className="detail-add" disabled={!product.stock} onClick={()=>addToCart(product)}>＋ Add to Cart</button><button className={saved?'detail-save saved':'detail-save'} onClick={toggleSave}>{saved?'♥ Saved':'♡ Save'}</button><button className="detail-share" onClick={share}>↗ Share</button></div><div className="detail-trust"><span>🚚 Local fulfilment</span><span>↩ Support for eligible issues</span><span>🔒 Secure account checkout</span></div></div></section>{related.length>0&&<section className="related-products"><div><span>YOU MAY ALSO LIKE</span><h2>More from {product.category}</h2></div><div className="product-grid">{related.map(p=><ProductCard key={p._id} product={p}/>)}</div></section>}</main>}
