import {useEffect,useMemo,useState} from 'react';
import {adminApi} from '../api';
import '../growth-admin.css';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const stars=n=>'★★★★★'.slice(0,Math.round(Number(n)||0))+'☆☆☆☆☆'.slice(0,5-Math.round(Number(n)||0));
export default function Growth(){
  const [orders,setOrders]=useState([]);const [customers,setCustomers]=useState([]);const [offers,setOffers]=useState([]);const [reviews,setReviews]=useState([]);const [error,setError]=useState('');
  const load=()=>Promise.all([adminApi('/admin/orders'),adminApi('/admin/customers'),adminApi('/admin/offers'),adminApi('/admin/reviews')]).then(([o,c,f,r])=>{setOrders(o);setCustomers(c);setOffers(f);setReviews(r)}).catch(e=>setError(e.message));
  useEffect(()=>{load()},[]);
  const data=useMemo(()=>{
    const valid=orders.filter(o=>o.status!=='Cancelled');const productMap=new Map();const customerMap=new Map();
    for(const o of valid){const uid=String(o.user?._id||o.user||'');if(uid)customerMap.set(uid,(customerMap.get(uid)||0)+1);for(const i of o.items||[]){const key=String(i.product?._id||i.product||i.name);const x=productMap.get(key)||{name:i.name,qty:0,revenue:0};x.qty+=Number(i.quantity)||0;x.revenue+=(Number(i.price)||0)*(Number(i.quantity)||0);productMap.set(key,x)}}
    const topProducts=[...productMap.values()].sort((a,b)=>b.qty-a.qty).slice(0,6);const repeat=[...customerMap.values()].filter(n=>n>1).length;const referrals=customers.filter(c=>c.referredBy).length;const topReferrers=[...customers].filter(c=>c.referralCount>0).sort((a,b)=>b.referralCount-a.referralCount).slice(0,5);const approved=reviews.filter(r=>r.approved);const avg=approved.length?Math.round((approved.reduce((s,r)=>s+r.rating,0)/approved.length)*10)/10:0;const couponUses=offers.reduce((s,o)=>s+(o.usedCount||0),0);return{topProducts,repeat,referrals,topReferrers,avg,couponUses}
  },[orders,customers,offers,reviews]);
  async function toggle(r){try{await adminApi(`/admin/reviews/${r._id}`,{method:'PATCH',body:JSON.stringify({approved:!r.approved})});load()}catch(e){alert(e.message)}}
  async function remove(r){if(!confirm('Delete this customer review?'))return;try{await adminApi(`/admin/reviews/${r._id}`,{method:'DELETE'});load()}catch(e){alert(e.message)}}
  return <><div className="admin-title"><div><small>STORE GROWTH</small><h1>Growth, Loyalty & Reviews</h1><p>Understand repeat business, referrals, product demand, campaigns and customer feedback.</p></div></div>{error&&<div className="admin-alert">{error}</div>}
    <section className="growth-kpis"><div><small>REPEAT CUSTOMERS</small><b>{data.repeat}</b></div><div><small>REFERRED SIGNUPS</small><b>{data.referrals}</b></div><div><small>COUPON USES</small><b>{data.couponUses}</b></div><div><small>AVG PRODUCT RATING</small><b>{data.avg?`${data.avg}/5`:'—'}</b></div></section>
    <div className="growth-layout"><section className="panel"><div className="panel-head"><h2>Top products</h2><small>By units ordered</small></div><div className="growth-list">{data.topProducts.map((p,i)=><article key={p.name}><div><b>#{i+1} {p.name}</b><small>{p.qty} units ordered</small></div><strong>{money(p.revenue)}</strong></article>)}{!data.topProducts.length&&<p>No order data yet.</p>}</div></section><section className="panel"><div className="panel-head"><h2>Referral leaders</h2><small>Customers bringing new signups</small></div><div className="growth-list">{data.topReferrers.map((c,i)=><article key={c._id}><div><b>#{i+1} {c.name}</b><small>{c.email}</small></div><strong>{c.referralCount} invite{c.referralCount===1?'':'s'}</strong></article>)}{!data.topReferrers.length&&<p>No tracked referrals yet.</p>}</div></section></div>
    <section className="panel growth-reviews"><div className="panel-head"><h2>Customer reviews</h2><small>{reviews.length} total · hide misleading/abusive content when needed</small></div><div className="growth-review-list">{reviews.map(r=><article key={r._id}><div className="growth-review-product">{r.product?.image&&<img src={r.product.image} alt=""/>}<div><b>{r.product?.name||'Product'}</b><small>{r.user?.name||'Customer'} · {r.verifiedPurchase?'Verified purchase':'Unverified purchase'}</small></div></div><div className="growth-review-copy"><strong>{stars(r.rating)}</strong>{r.title&&<b>{r.title}</b>}<p>{r.comment||'Rating only'}</p></div><div className="review-admin-actions"><button className={r.approved?'hide':'show'} onClick={()=>toggle(r)}>{r.approved?'Hide':'Show'}</button><button className="delete" onClick={()=>remove(r)}>Delete</button></div></article>)}{!reviews.length&&<p>No reviews yet.</p>}</div></section>
  </>
}
