import {useEffect,useMemo,useState} from 'react';
import {adminApi} from '../api';
import '../growth-admin.css';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const stars=n=>'★★★★★'.slice(0,Math.round(Number(n)||0))+'☆☆☆☆☆'.slice(0,5-Math.round(Number(n)||0));
export default function Growth(){
  const [orders,setOrders]=useState([]);const [customers,setCustomers]=useState([]);const [offers,setOffers]=useState([]);const [reviews,setReviews]=useState([]);const [reviewFilter,setReviewFilter]=useState('pending');const [error,setError]=useState('');
  const load=()=>Promise.all([adminApi('/admin/orders'),adminApi('/admin/customers'),adminApi('/admin/offers'),adminApi('/admin/reviews')]).then(([o,c,f,r])=>{setOrders(o);setCustomers(c);setOffers(f);setReviews(r)}).catch(e=>setError(e.message));
  useEffect(()=>{load()},[]);
  const data=useMemo(()=>{
    const valid=orders.filter(o=>o.status!=='Cancelled');const productMap=new Map();const customerMap=new Map();
    for(const o of valid){const uid=String(o.user?._id||o.user||'');if(uid)customerMap.set(uid,(customerMap.get(uid)||0)+1);for(const i of o.items||[]){const key=String(i.product?._id||i.product||i.name);const x=productMap.get(key)||{name:i.name,qty:0,revenue:0};x.qty+=Number(i.quantity)||0;x.revenue+=(Number(i.price)||0)*(Number(i.quantity)||0);productMap.set(key,x)}}
    const topProducts=[...productMap.values()].sort((a,b)=>b.qty-a.qty).slice(0,6);const repeat=[...customerMap.values()].filter(n=>n>1).length;const referrals=customers.filter(c=>c.referredBy).length;const topReferrers=[...customers].filter(c=>c.referralCount>0).sort((a,b)=>b.referralCount-a.referralCount).slice(0,5);const approved=reviews.filter(r=>r.approved);const avg=approved.length?Math.round((approved.reduce((s,r)=>s+r.rating,0)/approved.length)*10)/10:0;const couponUses=offers.reduce((s,o)=>s+(o.usedCount||0),0);return{topProducts,repeat,referrals,topReferrers,avg,couponUses,pending:reviews.filter(r=>!r.approved).length,live:approved.length}
  },[orders,customers,offers,reviews]);
  const filteredReviews=useMemo(()=>reviews.filter(r=>reviewFilter==='pending'?!r.approved:reviewFilter==='live'?r.approved:reviewFilter==='low'?Number(r.rating)<=2:true),[reviews,reviewFilter]);
  async function toggle(r){try{await adminApi(`/admin/reviews/${r._id}`,{method:'PATCH',body:JSON.stringify({approved:!r.approved})});load()}catch(e){alert(e.message)}}
  async function remove(r){if(!confirm('Delete this customer rating/suggestion permanently?'))return;try{await adminApi(`/admin/reviews/${r._id}`,{method:'DELETE'});load()}catch(e){alert(e.message)}}
  return <><div className="admin-title"><div><small>STORE GROWTH</small><h1>Growth, Loyalty & Reviews</h1><p>Customer feedback stays private until an admin approves it for the Store.</p></div></div>{error&&<div className="admin-alert">{error}</div>}
    <section className="growth-kpis"><div><small>REPEAT CUSTOMERS</small><b>{data.repeat}</b></div><div><small>PENDING REVIEWS</small><b>{data.pending}</b></div><div><small>LIVE REVIEWS</small><b>{data.live}</b></div><div><small>AVG LIVE RATING</small><b>{data.avg?`${data.avg}/5`:'—'}</b></div></section>
    <div className="growth-layout"><section className="panel"><div className="panel-head"><h2>Top products</h2><small>By units ordered</small></div><div className="growth-list">{data.topProducts.map((p,i)=><article key={p.name}><div><b>#{i+1} {p.name}</b><small>{p.qty} units ordered</small></div><strong>{money(p.revenue)}</strong></article>)}{!data.topProducts.length&&<p>No order data yet.</p>}</div></section><section className="panel"><div className="panel-head"><h2>Referral leaders</h2><small>Customers bringing new signups</small></div><div className="growth-list">{data.topReferrers.map((c,i)=><article key={c._id}><div><b>#{i+1} {c.name}</b><small>{c.email}</small></div><strong>{c.referralCount} invite{c.referralCount===1?'':'s'}</strong></article>)}{!data.topReferrers.length&&<p>No tracked referrals yet.</p>}</div></section></div>
    <section className="panel growth-reviews"><div className="panel-head review-panel-head"><div><h2>Customer ratings & suggestions</h2><small>New feedback is Pending by default. Only items you approve are visible to customers on the Store.</small></div><div className="review-filter-tabs"><button className={reviewFilter==='pending'?'active':''} onClick={()=>setReviewFilter('pending')}>Pending ({data.pending})</button><button className={reviewFilter==='live'?'active':''} onClick={()=>setReviewFilter('live')}>Live ({data.live})</button><button className={reviewFilter==='low'?'active':''} onClick={()=>setReviewFilter('low')}>Low rating</button><button className={reviewFilter==='all'?'active':''} onClick={()=>setReviewFilter('all')}>All</button></div></div><div className="growth-review-list">{filteredReviews.map(r=><article key={r._id} className={Number(r.rating)<=2?'low-review':''}><div className="growth-review-product">{r.product?.image&&<img src={r.product.image} alt=""/>}<div><b>{r.product?.name||'Product'}</b><small>{r.user?.name||'Customer'} · {r.verifiedPurchase?'Verified delivered purchase':'Unverified'}</small><span className={r.approved?'review-status-live':'review-status-pending'}>{r.approved?'LIVE ON STORE':'PENDING APPROVAL'}</span>{Number(r.rating)<=2&&<span className="negative-review-badge">Needs attention</span>}</div></div><div className="growth-review-copy"><strong>{stars(r.rating)}</strong>{r.title&&<b>{r.title}</b>}<p>{r.comment||'Rating only'}</p></div><div className="review-admin-actions"><button className={r.approved?'hide':'show'} onClick={()=>toggle(r)}>{r.approved?'Hide from Store':'Approve & Publish'}</button><button className="delete" onClick={()=>remove(r)}>Delete</button></div></article>)}{!filteredReviews.length&&<p>No feedback in this filter.</p>}</div></section>
  </>
}
