import {useEffect,useMemo,useState} from 'react';
import {adminApi} from '../api';
import '../paylater-kyc-admin.css';

const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const PRESETS=[
  {key:'extra_id',label:'Additional ID proof',type:'document',documentType:'ANY',prompt:'Upload the additional masked/redacted ID proof requested by store management.'},
  {key:'address_proof',label:'Address proof',type:'document',documentType:'ADDRESS_PROOF',prompt:'Upload a recent address proof such as utility bill or other acceptable document.'},
  {key:'business_proof',label:'Business / shop proof',type:'document',documentType:'BUSINESS_PROOF',prompt:'Upload the requested business/shop proof document.'},
  {key:'alt_phone',label:'Alternate mobile number',type:'phone',prompt:'Provide an alternate reachable mobile number.'},
  {key:'address_details',label:'Additional address details',type:'textarea',prompt:'Provide the additional address/location details requested by store management.'},
  {key:'repayment_info',label:'Repayment / income information',type:'textarea',prompt:'Provide only the information requested by store management. Do not enter bank passwords, PINs or OTPs.'}
];

export default function PayLaterKyc(){
  const [apps,setApps]=useState([]);const [selectedId,setSelectedId]=useState(null);const [detail,setDetail]=useState(null);const [note,setNote]=useState('');const [limit,setLimit]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [selectedPresets,setSelectedPresets]=useState([]);const [customLabel,setCustomLabel]=useState('');const [customType,setCustomType]=useState('text');const [customPrompt,setCustomPrompt]=useState('');
  const load=()=>adminApi('/admin/paylater-applications').then(setApps).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
  const selected=useMemo(()=>apps.find(a=>String(a.user?._id||a.user)===selectedId)||null,[apps,selectedId]);
  async function loadDetail(id=selectedId){if(!id)return;const d=await adminApi(`/admin/paylater/${id}/application`);setDetail(d);setLimit(String(d.user?.payLater?.limit||d.requestedLimit||0));setNote(d.verificationNote||'')}
  useEffect(()=>{if(!selectedId){setDetail(null);return}setDetail(null);setSelectedPresets([]);setCustomLabel('');setCustomPrompt('');loadDetail(selectedId).catch(e=>setError(e.message))},[selectedId]);
  async function saveVerify(key,value){if(!detail)return;setBusy(true);try{const d=await adminApi(`/admin/paylater/${selectedId}/application`,{method:'PATCH',body:JSON.stringify({[key]:value,verificationNote:note,status:'under_review'})});setDetail(x=>({...x,...d}));await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
  async function saveNote(){if(!detail)return;setBusy(true);try{const d=await adminApi(`/admin/paylater/${selectedId}/application`,{method:'PATCH',body:JSON.stringify({verificationNote:note,status:detail.status==='needs_update'?'needs_update':'under_review'})});setDetail(x=>({...x,...d}));await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
  async function decide(decision){if(!detail)return;if(decision==='approve'&&!confirm(`Approve PayLater for ${detail.user?.name} with limit ${money(limit)}?`))return;if(decision==='reject'&&!confirm('Reject this PayLater application?'))return;setBusy(true);try{await adminApi(`/admin/paylater/${selectedId}/decision`,{method:'POST',body:JSON.stringify({decision,limit:Number(limit),note})});setSelectedId(null);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
  function call(){if(!detail?.phone)return alert('Phone number unavailable');window.location.href=`tel:${detail.phone}`}
  function togglePreset(key){setSelectedPresets(x=>x.includes(key)?x.filter(k=>k!==key):[...x,key])}
  async function requestMore(){
    const requirements=PRESETS.filter(p=>selectedPresets.includes(p.key)).map(({label,type,documentType,prompt})=>({label,type,documentType,prompt,required:true}));
    if(customLabel.trim())requirements.push({label:customLabel.trim(),type:customType,documentType:customType==='document'?'OTHER':'ANY',prompt:customPrompt.trim(),required:true});
    if(!requirements.length)return alert('Select at least one requirement or add a custom question.');
    if(!confirm(`Send ${requirements.length} additional information request(s) to ${detail?.user?.name}?`))return;
    setBusy(true);try{await adminApi(`/admin/paylater/${selectedId}/requirements`,{method:'POST',body:JSON.stringify({requirements,note:note||'Additional information is required to continue PayLater verification.'})});setSelectedPresets([]);setCustomLabel('');setCustomPrompt('');await Promise.all([load(),loadDetail()])}catch(e){alert(e.message)}finally{setBusy(false)}
  }
  async function reviewRequirement(r,action){const label=action==='accept'?'Accept this submitted information?':'Ask the customer to submit this information again?';if(!confirm(label))return;setBusy(true);try{await adminApi(`/admin/paylater/${selectedId}/requirements/${r._id}`,{method:'PATCH',body:JSON.stringify({action,prompt:r.prompt||''})});await Promise.all([load(),loadDetail()])}catch(e){alert(e.message)}finally{setBusy(false)}}
  const pending=apps.filter(a=>['submitted','under_review','needs_update'].includes(a.status)).length;

  return <><div className="admin-title"><div><small>PAYLATER VERIFICATION</small><h1>KYC Applications</h1><p>Review the one-time KYC application. If anything else is required, send a specific follow-up request instead of asking the customer to fill the original form again.</p></div><span>{pending} pending</span></div>{error&&<div className="admin-alert">{error}</div>}<div className="kyc-admin-kpis"><div><small>ALL APPLICATIONS</small><b>{apps.length}</b></div><div><small>WAITING REVIEW</small><b>{pending}</b></div><div><small>APPROVED</small><b>{apps.filter(a=>a.status==='approved').length}</b></div><div><small>NEEDS INFO</small><b>{apps.filter(a=>a.status==='needs_update').length}</b></div></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Requested</th><th>ID Proof</th><th>Phone</th><th>Address</th><th>Follow-up</th><th>Status</th><th></th></tr></thead><tbody>{apps.map(a=><tr key={a._id}><td><b>{a.user?.name||'Customer'}</b><small className="table-sub">{a.email}</small></td><td>{money(a.requestedLimit)}</td><td>{a.proof?.type?.replaceAll('_',' ')} •••• {a.proof?.last4}<small className="table-sub">{a.idVerified?'✓ Verified':'Pending'}</small></td><td>{a.phone}<small className="table-sub">{a.phoneVerified?'✓ Verified':'Pending'}</small></td><td>{a.address?.city}, {a.address?.pincode}<small className="table-sub">{a.addressVerified?'✓ Verified':'Pending'}</small></td><td>{(a.requirements||[]).filter(r=>r.status==='requested').length} requested<br/><small className="table-sub">{(a.requirements||[]).filter(r=>r.status==='submitted').length} submitted · {(a.requirements||[]).filter(r=>r.status==='accepted').length} accepted</small></td><td><span className={`kyc-admin-status ${a.status}`}>{a.status.replaceAll('_',' ')}</span></td><td><button className="manage-credit" onClick={()=>setSelectedId(String(a.user?._id||a.user))}>Review →</button></td></tr>)}</tbody></table></div></section><div className="management-note"><b>Privacy:</b> collect only what is actually required. For government IDs, request masked/redacted copies and never ask customers to type full Aadhaar/PAN/Voter ID numbers, passwords, PINs or OTPs.</div>

  {selected&&<div className="kyc-admin-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelectedId(null)}}><section className="kyc-admin-modal"><header><div><small>KYC REVIEW</small><h2>{selected.user?.name}</h2><p>{selected.phone} · {selected.email}</p></div><button onClick={()=>setSelectedId(null)}>×</button></header>{!detail?<div className="loading">Loading application...</div>:<>
    <div className="kyc-review-grid"><section><h3>Original identity proof</h3><p><b>{detail.proof?.type?.replaceAll('_',' ')}</b> ending <b>{detail.proof?.last4}</b></p><p>{detail.proof?.fileName} · {Math.round((detail.proof?.size||0)/1024)} KB</p>{detail.proof?.data&&(detail.proof.mimeType?.startsWith('image/')?<img className="kyc-proof-preview" src={detail.proof.data} alt="Masked identity proof"/>:<a className="kyc-proof-link" href={detail.proof.data} target="_blank" rel="noreferrer">Open masked PDF proof ↗</a>)}<label className="kyc-check"><input type="checkbox" checked={Boolean(detail.idVerified)} onChange={e=>saveVerify('idVerified',e.target.checked)} disabled={busy}/><span>ID proof manually verified</span></label></section><section><h3>Address & contact</h3><p><b>{detail.phone}</b><br/>{detail.email}</p><p>{[detail.address?.houseNo,detail.address?.locality,detail.address?.landmark,detail.address?.village,detail.address?.city,detail.address?.district,detail.address?.state,detail.address?.pincode].filter(Boolean).join(', ')}</p><div className="kyc-contact-actions"><button onClick={call}>☎ Call customer</button><a href={`mailto:${detail.email}`}>✉ Email</a></div><label className="kyc-check"><input type="checkbox" checked={Boolean(detail.phoneVerified)} onChange={e=>saveVerify('phoneVerified',e.target.checked)} disabled={busy}/><span>Phone manually verified</span></label><label className="kyc-check"><input type="checkbox" checked={Boolean(detail.addressVerified)} onChange={e=>saveVerify('addressVerified',e.target.checked)} disabled={busy}/><span>Address manually verified</span></label></section></div>

    {(detail.requirements||[]).length>0&&<section className="kyc-decision" style={{display:'block'}}><h3>Additional information history</h3><div className="kyc-review-grid">{detail.requirements.map(r=><section key={r._id}><div className={`kyc-admin-status ${r.status==='accepted'?'approved':r.status==='requested'?'needs_update':'under_review'}`}>{r.status.replaceAll('_',' ')}</div><h3>{r.label}</h3>{r.prompt&&<p>{r.prompt}</p>}{r.type==='document'?<>{r.file?.data?(r.file.mimeType?.startsWith('image/')?<img className="kyc-proof-preview" src={r.file.data} alt={r.label}/>:<a className="kyc-proof-link" href={r.file.data} target="_blank" rel="noreferrer">Open submitted document ↗</a>):<p>{r.file?.fileName||'Waiting for customer upload'}</p>}</>:<p><b>{r.value||'Waiting for customer response'}</b></p>}{r.status==='submitted'&&<div className="kyc-decision-actions"><button className="approve" onClick={()=>reviewRequirement(r,'accept')} disabled={busy}>Accept Information</button><button className="needs" onClick={()=>reviewRequirement(r,'ask_again')} disabled={busy}>Ask Again</button></div>}</section>)}</div></section>}

    {detail.status!=='approved'&&detail.status!=='rejected'&&<section className="kyc-decision" style={{display:'block'}}><h3>Request more information</h3><p style={{fontSize:11,color:'#66756b'}}>Choose exactly what is required. A separate form will automatically appear in the customer’s PayLater page. The original KYC form stays locked.</p><div className="kyc-review-grid">{PRESETS.map(p=><label className="kyc-check" key={p.key}><input type="checkbox" checked={selectedPresets.includes(p.key)} onChange={()=>togglePreset(p.key)} disabled={busy}/><span><b>{p.label}</b><br/>{p.prompt}</span></label>)}</div><div className="kyc-review-grid"><section><h3>Custom requirement</h3><label>Field label<input value={customLabel} onChange={e=>setCustomLabel(e.target.value)} placeholder="Example: Father's / guardian contact"/></label><label>Field type<select value={customType} onChange={e=>setCustomType(e.target.value)}><option value="text">Short text</option><option value="textarea">Long text</option><option value="phone">Phone</option><option value="email">Email</option><option value="document">Document upload</option></select></label></section><section><h3>Customer instruction</h3><label>Instruction / reason<textarea value={customPrompt} onChange={e=>setCustomPrompt(e.target.value)} placeholder="Explain exactly what should be submitted and why."/></label></section></div><div className="kyc-decision-actions"><button className="needs" onClick={requestMore} disabled={busy}>Request Selected Information</button></div></section>}

    <section className="kyc-decision"><div><label>Approved limit<input type="number" min="1" value={limit} onChange={e=>setLimit(e.target.value)}/></label><small>Customer requested {money(detail.requestedLimit)}</small></div><label>Verification / decision note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Factual verification notes only; do not paste full government ID numbers."/></label><div className="kyc-decision-actions"><button onClick={saveNote} disabled={busy}>Save Review Note</button><button className="reject" onClick={()=>decide('reject')} disabled={busy}>Reject</button><button className="approve" onClick={()=>decide('approve')} disabled={busy}>Approve & Set Limit</button></div></section><div className="kyc-credit-note"><b>Approval rule:</b> original ID, phone and address must be verified, and every additional information request must be accepted before approval. Credit-bureau scoring is not connected.</div>
  </>}</section></div>}</>}
