import {useEffect,useState} from 'react';
import {adminApi} from '../api';

const blank={name:'',email:'',phone:'',password:''};
export default function PosStaff(){
  const [users,setUsers]=useState([]),[form,setForm]=useState(blank),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  async function load(){try{setUsers(await adminApi('/admin/pos-users'))}catch(e){setError(e.message)}}
  useEffect(()=>{load()},[]);
  async function create(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{await adminApi('/admin/pos-users',{method:'POST',body:JSON.stringify(form)});setForm(blank);setMessage('POS staff login created');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function toggle(user){setError('');try{await adminApi(`/admin/pos-users/${user._id}`,{method:'PATCH',body:JSON.stringify({isActive:!user.isActive})});await load()}catch(e){setError(e.message)}}
  async function signout(user){if(!confirm(`Sign out ${user.name} from all POS devices?`))return;setError('');try{await adminApi(`/admin/pos-users/${user._id}/signout`,{method:'POST',body:'{}'});setMessage(`${user.name} signed out from all POS devices`);await load()}catch(e){setError(e.message)}}
  async function resetPassword(user){const password=prompt(`Enter a new strong password for ${user.name}`);if(!password)return;setError('');try{await adminApi(`/admin/pos-users/${user._id}/password`,{method:'POST',body:JSON.stringify({password})});setMessage(`Password changed for ${user.name}. Previous POS sessions were signed out.`)}catch(e){setError(e.message)}}
  return <><div className="admin-title"><div><small>ACCESS CONTROL</small><h1>POS Staff</h1><p>Create restricted cashier logins for the separate POS Billing portal.</p></div><span>{users.filter(u=>u.isActive).length} active</span></div>{error&&<div className="admin-alert">{error}</div>}{message&&<div className="admin-note">{message}</div>}<div className="management-grid"><form className="panel management-form" onSubmit={create}><div className="panel-head"><h2>Create POS login</h2><small>POS-only permissions</small></div><label>Staff name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email / Login ID<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Temporary password<input type="password" required minLength="10" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><p className="form-help">Use a unique strong password. This account cannot access Products, Customers, PayLater, Security Center or Admin Management.</p><button disabled={busy}>{busy?'Creating...':'Create POS Staff Login'}</button></form><section className="panel"><div className="panel-head"><h2>POS access accounts</h2><small>Connected to the same inventory & sales database</small></div><div className="management-list">{users.map(u=><article key={u._id}><div><b>{u.name}</b><small>{u.email}{u.phone?` · ${u.phone}`:''}</small><span className={u.isActive?'status-approved':'status-banned'}>{u.isActive?'ACTIVE':'DISABLED'}</span></div><div className="management-actions"><button onClick={()=>resetPassword(u)}>Change Password</button><button onClick={()=>signout(u)}>Logout All Devices</button><button className={u.isActive?'danger':''} onClick={()=>toggle(u)}>{u.isActive?'Disable':'Enable'}</button></div></article>)}{!users.length&&<p>No POS staff accounts yet.</p>}</div></section></div></>;
}
