import {useEffect,useState} from 'react';
import {adminApi} from '../api';
import {useAdminAuth} from '../context/AdminAuthContext';
import '../security-center.css';

const when=value=>value?new Date(value).toLocaleString('en-IN'):'—';
const outcomeLabel=value=>({success:'Successful login',password_failed:'Wrong password',two_factor_required:'Password accepted · 2FA required',two_factor_failed:'2FA failed',account_disabled:'Disabled account attempt'}[value]||value);

export default function SecurityCenter(){
  const {admin,updateSession,logout}=useAdminAuth();
  const [overview,setOverview]=useState(null);const [audit,setAudit]=useState([]);const [setup,setSetup]=useState(null);const [enableCode,setEnableCode]=useState('');const [recoveryCodes,setRecoveryCodes]=useState([]);const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState('');
  const [passwordForm,setPasswordForm]=useState({currentPassword:'',newPassword:'',confirm:''});
  const [recoveryForm,setRecoveryForm]=useState({password:'',code:''});
  const [disableForm,setDisableForm]=useState({password:'',code:''});
  const load=()=>Promise.all([adminApi('/auth/security'),adminApi('/admin/audit-logs')]).then(([security,logs])=>{setOverview(security);setAudit(logs||[])}).catch(e=>setError(e.message));
  useEffect(()=>{load()},[]);
  function clear(){setMessage('');setError('')}
  async function startSetup(){clear();setBusy('setup');try{const data=await adminApi('/auth/2fa/setup',{method:'POST',body:'{}'});setSetup(data)}catch(e){setError(e.message)}finally{setBusy('')}}
  async function enable2fa(e){e.preventDefault();clear();setBusy('enable');try{const data=await adminApi('/auth/2fa/enable',{method:'POST',body:JSON.stringify({code:enableCode})});updateSession(data);setRecoveryCodes(data.recoveryCodes||[]);setSetup(null);setEnableCode('');setMessage('Two-factor authentication is now enabled. Save the recovery codes somewhere private.');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
  async function changePassword(e){e.preventDefault();clear();if(passwordForm.newPassword!==passwordForm.confirm)return setError('New password and confirmation do not match');setBusy('password');try{const data=await adminApi('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:passwordForm.currentPassword,newPassword:passwordForm.newPassword})});updateSession(data);setPasswordForm({currentPassword:'',newPassword:'',confirm:''});setMessage(data.message);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
  async function regenerate(e){e.preventDefault();clear();setBusy('recovery');try{const data=await adminApi('/auth/2fa/recovery-codes',{method:'POST',body:JSON.stringify(recoveryForm)});setRecoveryCodes(data.recoveryCodes||[]);setRecoveryForm({password:'',code:''});setMessage(data.message);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
  async function disable2fa(e){e.preventDefault();clear();if(!confirm('Disable two-factor authentication for this admin account?'))return;setBusy('disable');try{const data=await adminApi('/auth/2fa/disable',{method:'POST',body:JSON.stringify(disableForm)});updateSession(data);setDisableForm({password:'',code:''});setRecoveryCodes([]);setMessage(data.message);await load()}catch(e){setError(e.message)}finally{setBusy('')}}
  async function logoutEverywhere(){clear();if(!confirm('Sign out this admin account from every device, including this browser?'))return;setBusy('logout');try{await adminApi('/auth/logout-all',{method:'POST',body:'{}'});logout()}catch(e){setError(e.message);setBusy('')}}
  async function copy(value){try{await navigator.clipboard.writeText(value);setMessage('Copied to clipboard.')}catch{setError('Could not copy automatically. Select and copy it manually.')}}
  const twoFactor=overview?.twoFactor||{};
  return <><div className="admin-title"><div><small>ACCOUNT SECURITY</small><h1>Admin Security Center</h1><p>Protect {admin?.email} with two-factor authentication, session controls and security history.</p></div></div>{error&&<div className="admin-alert">{error}</div>}{message&&<div className="security-success">{message}</div>}
    <section className="security-kpis"><div><small>2FA STATUS</small><b className={twoFactor.enabled?'secure-on':'secure-off'}>{twoFactor.enabled?'Protected':'Not enabled'}</b></div><div><small>RECOVERY CODES</small><b>{twoFactor.enabled?twoFactor.recoveryCodesRemaining:'—'}</b></div><div><small>PASSWORD CHANGED</small><b>{overview?.lastPasswordChangedAt?new Date(overview.lastPasswordChangedAt).toLocaleDateString('en-IN'):'—'}</b></div><div><small>RECENT LOGIN EVENTS</small><b>{overview?.loginHistory?.length||0}</b></div></section>
    <div className="security-grid">
      <section className="security-card"><div className="security-card-head"><div><span>🔐</span><div><h2>Authenticator 2FA</h2><p>Google Authenticator, Microsoft Authenticator and compatible TOTP apps.</p></div></div><b className={twoFactor.enabled?'security-badge on':'security-badge'}>{twoFactor.enabled?'ENABLED':'OFF'}</b></div>
        {!twoFactor.enabled&&!setup&&<button className="security-primary" disabled={busy==='setup'} onClick={startSetup}>{busy==='setup'?'Preparing...':'Set up Authenticator →'}</button>}
        {!twoFactor.enabled&&setup&&<form className="security-form" onSubmit={enable2fa}><div className="setup-key"><small>MANUAL SETUP KEY</small><code>{setup.secret}</code><button type="button" onClick={()=>copy(setup.secret)}>Copy key</button></div><p className="security-hint">Open your Authenticator app → Add account → Enter setup key. Then enter the 6-digit code below. Setup expires in about 10 minutes.</p><label>6-digit authenticator code<input inputMode="numeric" autoComplete="one-time-code" required value={enableCode} onChange={e=>setEnableCode(e.target.value)} placeholder="123456"/></label><button className="security-primary" disabled={busy==='enable'}>{busy==='enable'?'Verifying...':'Verify & Enable 2FA'}</button></form>}
        {twoFactor.enabled&&<><div className="security-info-row"><span>Enabled</span><b>{when(twoFactor.enabledAt)}</b></div><div className="security-info-row"><span>Recovery codes remaining</span><b>{twoFactor.recoveryCodesRemaining}</b></div><form className="security-form compact" onSubmit={regenerate}><h3>Generate new recovery codes</h3><label>Current password<input type="password" required value={recoveryForm.password} onChange={e=>setRecoveryForm({...recoveryForm,password:e.target.value})}/></label><label>Authenticator / recovery code<input required value={recoveryForm.code} onChange={e=>setRecoveryForm({...recoveryForm,code:e.target.value})}/></label><button disabled={busy==='recovery'}>{busy==='recovery'?'Generating...':'Generate New Codes'}</button></form><form className="security-form compact danger-zone" onSubmit={disable2fa}><h3>Disable 2FA</h3><p>Only do this if you are changing your security setup.</p><label>Current password<input type="password" required value={disableForm.password} onChange={e=>setDisableForm({...disableForm,password:e.target.value})}/></label><label>Authenticator / recovery code<input required value={disableForm.code} onChange={e=>setDisableForm({...disableForm,code:e.target.value})}/></label><button disabled={busy==='disable'}>{busy==='disable'?'Disabling...':'Disable 2FA'}</button></form></>}
      </section>
      <section className="security-card"><div className="security-card-head"><div><span>🔑</span><div><h2>Change Password</h2><p>Changing the password signs out other sessions and keeps this browser secured with a new token.</p></div></div></div><form className="security-form" onSubmit={changePassword}><label>Current password<input type="password" autoComplete="current-password" required value={passwordForm.currentPassword} onChange={e=>setPasswordForm({...passwordForm,currentPassword:e.target.value})}/></label><label>New password<input type="password" autoComplete="new-password" minLength="10" required value={passwordForm.newPassword} onChange={e=>setPasswordForm({...passwordForm,newPassword:e.target.value})}/></label><label>Confirm new password<input type="password" autoComplete="new-password" minLength="10" required value={passwordForm.confirm} onChange={e=>setPasswordForm({...passwordForm,confirm:e.target.value})}/></label><small className="security-hint">Use 10+ characters and at least 3 types: uppercase, lowercase, number, special character.</small><button className="security-primary" disabled={busy==='password'}>{busy==='password'?'Updating...':'Change Password'}</button></form><div className="logout-all-box"><div><b>Logout All Devices</b><p>Immediately invalidates every active admin session, including this browser.</p></div><button onClick={logoutEverywhere} disabled={busy==='logout'}>{busy==='logout'?'Signing out...':'Logout All Devices'}</button></div></section>
    </div>
    {recoveryCodes.length>0&&<section className="security-card recovery-card"><div className="security-card-head"><div><span>🧾</span><div><h2>Save these recovery codes now</h2><p>Each code works once. They will not be shown again after you leave this page.</p></div></div></div><div className="recovery-code-grid">{recoveryCodes.map(code=><code key={code}>{code}</code>)}</div><button className="security-primary" onClick={()=>copy(recoveryCodes.join('\n'))}>Copy All Recovery Codes</button></section>}
    <section className="security-card security-table-card"><div className="security-card-head"><div><span>🕘</span><div><h2>Login History</h2><p>Successful and failed admin sign-in activity from the last 90 days.</p></div></div></div><div className="security-table"><div className="security-row head"><span>Time</span><span>Result</span><span>IP</span><span>Device</span></div>{(overview?.loginHistory||[]).map(row=><div className="security-row" key={row._id}><span>{when(row.createdAt)}</span><span className={`login-outcome ${row.outcome==='success'?'ok':row.outcome.includes('failed')?'bad':'warn'}`}>{outcomeLabel(row.outcome)}</span><span>{row.ip||'—'}</span><span title={row.userAgent}>{row.userAgent||'Unknown'}</span></div>)}{!overview?.loginHistory?.length&&<p>No login history yet.</p>}</div></section>
    <section className="security-card security-table-card"><div className="security-card-head"><div><span>📋</span><div><h2>Admin Activity Audit Log</h2><p>Write actions such as product, stock, order, PayLater, billing and admin changes are recorded for accountability.</p></div></div></div><div className="security-table audit-table"><div className="security-row head"><span>Time</span><span>Admin</span><span>Action</span><span>Status</span></div>{audit.map(row=><div className="security-row" key={row._id}><span>{when(row.createdAt)}</span><span>{row.admin?.name||row.admin?.email||'Admin'}</span><span title={row.path}>{row.action}</span><span className={row.statusCode>=400?'audit-bad':'audit-ok'}>{row.statusCode||'—'}</span></div>)}{!audit.length&&<p>No admin activity recorded yet.</p>}</div></section>
  </>
}
